#ifndef __CRTTR_C_STANDARD_TYPES_H__
#define __CRTTR_C_STANDARD_TYPES_H__
#include "ccore/c_target.h"
#ifdef USE_PRAGMA_ONCE
#    pragma once
#endif

#include "crttr/c_type_info.h"
#include "crttr/c_rttr_enable.h"

RTTR_DECLARE_STANDARD_META_TYPE_VARIANTS(bool)
RTTR_DECLARE_STANDARD_META_TYPE_VARIANTS(int)
RTTR_DECLARE_STANDARD_META_TYPE_VARIANTS(unsigned int)
RTTR_DECLARE_STANDARD_META_TYPE_VARIANTS(char)
RTTR_DECLARE_STANDARD_META_TYPE_VARIANTS(unsigned char)
RTTR_DECLARE_STANDARD_META_TYPE_VARIANTS(short)
RTTR_DECLARE_STANDARD_META_TYPE_VARIANTS(unsigned short)
RTTR_DECLARE_STANDARD_META_TYPE_VARIANTS(long)
RTTR_DECLARE_STANDARD_META_TYPE_VARIANTS(unsigned long)
RTTR_DECLARE_STANDARD_META_TYPE_VARIANTS(float)
RTTR_DECLARE_STANDARD_META_TYPE_VARIANTS(double)

#endif // __RTTR_STANDARDTYPES_H__
